import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createCanvas,loadImage} from 'canvas';
import {defaultAdjustments,adjustPixels,transformPoint,localPoint,validateProject} from './editor-core.mjs';
import {makeRenderer} from './editor-renderer.mjs';
const fixture=()=>({format:'street-paint-project',version:1,width:64,height:64,layers:[]});
const layer=(id,src)=>({id,name:id,type:'image',src,x:0,y:0,w:64,h:64,scale:1,rotation:0,opacity:100,blend:'source-over',visible:true,locked:false,adjust:defaultAdjustments(),feather:{left:0,right:0,top:0,bottom:0}});
async function setup(){const bank=new Map(),cache=new Map();for(const [name,color]of [['red','#ff0000'],['blue','#0000ff']]){const c=createCanvas(64,64);const p=c.getContext('2d');p.fillStyle=color;p.fillRect(0,0,64,64);const url=c.toDataURL('image/png');bank.set(url,await loadImage(c.toBuffer('image/png')));bank.set(name,url);}return {bank,renderer:makeRenderer(createCanvas,bank,cache)};}
const pixel=(c,x,y)=>[...c.getContext('2d').getImageData(x,y,1,1).data];
test('identity adjustments preserve RGB and alpha, including transparent pixels',()=>{const data=new Uint8ClampedArray([12,143,250,72,0,255,128,0]);assert.deepEqual([...adjustPixels(data,defaultAdjustments())],[12,143,250,72,0,255,128,0]);});
test('saturation removal makes neutral RGB without changing alpha; exposure doubles channels',()=>{let a=adjustPixels(new Uint8ClampedArray([30,120,200,149]),{...defaultAdjustments(),saturation:0});assert.equal(a[0],a[1]);assert.equal(a[1],a[2]);assert.equal(a[3],149);a=adjustPixels(new Uint8ClampedArray([20,40,60,100]),{...defaultAdjustments(),exposure:1});assert.deepEqual([...a],[40,80,120,100]);});
test('rotated and scaled layer coordinate transforms round trip',()=>{const l={x:-80,y:90,scale:2.35,rotation:37};const p=transformPoint(l,221,80),q=localPoint(l,p.x,p.y);assert.ok(Math.abs(q.x-221)<1e-9);assert.ok(Math.abs(q.y-80)<1e-9);});
test('renderer respects layer order, opacity, hidden layers and translation',async()=>{const {bank,renderer}=await setup(),p=fixture(),a=layer('a',bank.get('red')),b=layer('b',bank.get('blue'));b.x=32;b.opacity=50;p.layers=[a,b];const c=renderer.compose(createCanvas(1,1),p);assert.deepEqual(pixel(c,10,20),[255,0,0,255]);const blend=pixel(c,40,20);assert.ok(Math.abs(blend[0]-127)<2&&Math.abs(blend[2]-128)<2);b.visible=false;renderer.compose(c,p);assert.deepEqual(pixel(c,40,20),[255,0,0,255]);});
test('left feather produces smooth alpha without mutating source color',async()=>{const {bank,renderer}=await setup(),l=layer('a',bank.get('red'));l.feather.left=50;const c=renderer.renderLayer(l);assert.ok(pixel(c,0,30)[3]<10);assert.ok(pixel(c,16,30)[3]>120&&pixel(c,16,30)[3]<145);assert.equal(pixel(c,40,30)[3],255);assert.equal(pixel(c,40,30)[0],255);});
test('color changes invalidate cached pixels; export encoding matches composed image',async()=>{const {bank,renderer}=await setup(),p=fixture(),l=layer('a',bank.get('red'));p.layers=[l];let c=renderer.compose(createCanvas(1,1),p);assert.equal(pixel(c,30,30)[0],255);l.adjust.exposure=-1;renderer.compose(c,p);assert.ok(Math.abs(pixel(c,30,30)[0]-128)<=1);const im=await loadImage(c.toBuffer('image/png'));const decoded=createCanvas(64,64);decoded.getContext('2d').drawImage(im,0,0);assert.deepEqual(pixel(decoded,30,30),pixel(c,30,30));});
test('difference blend and rotated text render through the same composition path',async()=>{const {bank,renderer}=await setup(),p=fixture();const a=layer('a',bank.get('red')),b=layer('b',bank.get('red'));b.blend='difference';p.layers=[a,b];const c=renderer.compose(createCanvas(64,64),p);assert.deepEqual(pixel(c,10,10),[0,0,0,255]);p.layers=[{id:'text',type:'text',text:'A',name:'text',fontSize:24,fontFamily:'sans-serif',color:'#ffffff',w:40,h:40,x:40,y:5,rotation:90,scale:1,opacity:100,visible:true,locked:false,blend:'source-over'}];renderer.compose(c,p);const pixels=c.getContext('2d').getImageData(0,0,64,64).data;assert.ok(pixels.some((v,i)=>i%4===3&&v>0));});
test('portable project round trip; reject remote assets, invalid masks and oversized canvas',async()=>{const {bank}=await setup(),p=fixture();p.layers=[layer('a',bank.get('red'))];assert.deepEqual(validateProject(JSON.parse(JSON.stringify(p))),p);assert.throws(()=>validateProject({...p,width:8192,height:8192}));assert.throws(()=>validateProject({...p,layers:[{...p.layers[0],src:'https://example.com/remote.png'}]}));assert.throws(()=>validateProject({...p,layers:[{...p.layers[0],feather:{left:200,right:0,top:0,bottom:0}}]}));});
